# Увеличиваем размер кеша и включаем LRU (Least Recently Used) для очистки
maxmemory 256mb
maxmemory-policy allkeys-lru

# Оптимизация производительности
tcp-backlog 511
timeout 0
tcp-keepalive 300

# Параметры сохранения данных
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfsync everysec

# Снижаем объем логов для производительности
loglevel warning
